[tool.poetry]
name = "prts"
version = "0.1.0"
description = ""
authors = ["rizawa <rizawa@ridge-i.com>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.19.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
